### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [dannygaray60/club_de_detectives_01#3]
Hi, I was wondering if you'd be willing to pick a license for your project. Licenses help others use your open source code in a way that respects your wishes as the author.

**Comment by pat-hwaki** [comment]
@dannygaray60 Hi, this is a wonderful game. Is the metadata presented on itch.io not quite clear though? (the metadata on the itch io said it is licensed under a MIT license. Though your customized license (for code) is probably a permissive license similar to MIT license. https://dannygaray60.itch.io/detective-school-club
![mod](https://github.com/user-attachments/assets/1451cf1f-0640-4b76-9d49-e147c151260a)

**Comment by dannygaray60** [comment]
Yes is MIT only the source code
